import { HiShoppingCart } from "react-icons/hi";

export const data1: Array<any> = [
  {
    icon: <HiShoppingCart />,
    img: "https://i.kinja-img.com/gawker-media/image/upload/t_original/ijsi5fzb1nbkbhxa2gc1.png",
    name: "Bored Ape Yacht Club",
    price: "6.969",
    quantity: "1",
    from: "jhon",
    to: "melissa",
    date: `a minute ago`,
  },
  {
    icon: <HiShoppingCart />,
    img: "https://www.nj.com/resizer/h8MrN0-Nw5dB5FOmMVGMmfVKFJo=/450x0/smart/cloudfront-us-east-1.images.arcpublishing.com/advancelocal/SJGKVE5UNVESVCW7BBOHKQCZVE.jpg",
    name: "Apparitions #149",
    price: "6.969",
    quantity: "14",
    from: "jhon",
    to: "melissa",
    date: `a minute ago`,
  },
  {
    icon: <HiShoppingCart />,
    img: "https://i.pinimg.com/originals/5e/50/fa/5e50fa16044abc13c3088987a07a7d9f.jpg",
    name: "Meebit #18944",
    price: "6.969",
    quantity: "1",
    from: "jhon",
    to: "melissa",
    date: `a minute ago`,
  },
  {
    icon: <HiShoppingCart />,
    img: "https://i.pinimg.com/originals/3f/33/ff/3f33ff4769eab90d507b1e9e83ca0f3e.png",
    name: "Picasso Slacker Duck #5",
    price: "6.969",
    quantity: "0.0092",
    from: "jhon",
    to: "melissa",
    date: `a minute ago`,
  },
  {
    icon: <HiShoppingCart />,
    img: "https://i.pinimg.com/originals/7b/4e/19/7b4e190ff7436071402d680d849c353d.png",
    name: "Bored Ape Yacht Club",
    price: "6.969",
    quantity: "6.9",
    from: "jhon",
    to: "melissa",
    date: "a minute ago",
  },
];
