const data: any = [
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    art: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    art: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    art: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    art: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    music: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    music: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    music: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    collectibles: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    collectibles: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    collectibles: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    sports: true,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    sports: true,
    time: 1657886400,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    sports: true,
    time: 1657886400,
  },
  {
    likes: 200,
    name: "Living Vase 01 By Lanz...",
    currency: "BBC",
    price: "4.89 ETH",
    creator: "Freddie Car...",
    time: 1657886400,
    sports: true,
  },
];

export default data;
